import { type ReactNode } from "react";
import { Center, Title } from "@mantine/core";
import Head from "next/head";

export default function Home(): ReactNode {
  return (
    <>
      <Head>
        <title>Qin App Team A</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Center>
        <Title sx={{ color: "red" }}>Hello World</Title>
      </Center>
    </>
  );
}
