name: "Chromatic"

on:
  push:
    branches:
      - "develop"

  pull_request:
    branches:
      - "develop"

jobs:
  chromatic-deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Install dependencies
        run: npm
        with:
          workingDir: frontend

      - name: Publish Project to Chromatic
        uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
