name: "CI"

on:
  push:
    branches:
      - "develop"
    paths:
      - "frontend/**"
  pull_request:
    branches:
      - "develop"
    paths:
      - "frontend/**"

jobs:
  chromatic_deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Install dependencies
        run: npm ci
        working-directory: frontend

      - name: Build Storybook
        run: npm run build-storybook
        working-directory: frontend

      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          workingDir: frontend
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Install Dependencies
        run: npm ci
        working-directory: frontend

      - name: Run lint
        run: npm run lint
        working-directory: frontend
